project_id = "bigrgsmwbqvjroaoixfj"

[functions.verify-sol-transaction]
verify_jwt = false

[functions.generate-tweet]
verify_jwt = false

[functions.post-tweet]
verify_jwt = false

[functions.auto-post]
verify_jwt = false

[functions.auto-reply]
verify_jwt = false

[functions.sol-donation-tweet]
verify_jwt = false

[functions.manage-agent]
verify_jwt = false

[functions.admin-tweet-actions]
verify_jwt = false

[functions.send-global-message]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-hunter]
verify_jwt = false
