project_id = "bigrgsmwbqvjroaoixfj"

[functions.verify-sol-transaction]
verify_jwt = false

[functions.generate-tweet]
verify_jwt = false

[functions.post-tweet]
verify_jwt = false

[functions.auto-post]
verify_jwt = false

[functions.auto-reply]
verify_jwt = false

[functions.sol-donation-tweet]
verify_jwt = false

[functions.manage-agent]
verify_jwt = false

[functions.admin-tweet-actions]
verify_jwt = false

[functions.send-global-message]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-hunter]
verify_jwt = false

[functions.post-pending-tweets]
verify_jwt = false

[functions.trend-intelligence]
verify_jwt = false

[functions.auto-follow]
verify_jwt = false

[functions.generate-media-post]
verify_jwt = false

[functions.tts-speak]
verify_jwt = false

[functions.merge-video]
verify_jwt = false

[functions.async-media-worker]
verify_jwt = false

[functions.market-watchdog]
verify_jwt = false

[functions.social-pulse]
verify_jwt = false

[functions.flash-snipe]
verify_jwt = false

